### ISSUE TITLE
Slackbot demo ? 

### ISSUE THREAD

**Issue by dirakx1** [lamini-ai/lamini-sdk#77]
I think the readme should be expanded to add the slack installation procedure. Although app.py has the important beats, it's somewhat cumbersome to know how to install and run the app on slack.

**Comment by edamamez** [comment]
Added, thank you for your feedback!

https://github.com/lamini-ai/lamini-sdk/commit/3467ae12fe67dd54dc39e2a4428fe26f1ffea9a6

**Comment by dirakx1** [comment]
Ty this is a great advane @edamamez , anyway after following up the updated instructions, the bot doesnt get answers for example:
 ```
⚡️ Bolt app is running!
Mentioned in channel C0798PSKK3K with question  hello
Model names: ['meta-llama/Llama-2-7b-chat-hf']
'Answer'
```
And in slack .. it gets stalled on _Typing..._
